name: Build revanced-integrations (APK)

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Build (APK)
        run: |
          chmod +x ./gradlew || true
          ./gradlew --no-daemon :app:assembleRelease

      - name: Upload artifact (integrations APK)
        uses: actions/upload-artifact@v4
        with:
          name: revanced-integrations-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 14
